# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Predicting merchant churn in traditional FMCG supply chain
tagline:          ''
description:      'A group project of Math-493 for practicing data science life cycle' 
url:              "https://yingli.github.io"
baseurl:          "/math493-fall2022"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/yingli/math493-fall2022/
