# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Data Science Life Cycle Group Project
tagline:          ''
description:      'The group project on practicing data science life cycle' 
url:              "https://yingli.github.io"
baseurl:          "/math493-fall2022"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/yingli/math493-fall2022/
